out_dir: results
metric_best: mae
metric_agg: argmin
num_workers: 12
wandb:
  use: True
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 100
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_mp: 11
  layers_post_mp: 2
  dim_inner: 80
  layer_type: gensconv
  act: gelu
  residual: True
  dropout: 0.045
  batchnorm: True
  agg: add
  pre_gnn_type: 'mlp'
  gens:
    hop_att: True
    K: 3
    gamma: 0.7
    fea_drop: simple
    base_model: gat
    concat: True
    heads: 4
    edge_dim: 80
    att_dropout: 0.0
    use_ffN: True
    diff_alpha: False
    norm_type: "batch"
optim:
#  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 20
