out_dir: results
metric_best: f1
wandb:
  use: True
  project: Pascal
dataset:
  format: PyG-VOCSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: VOCNode+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: VOCEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
#  neighbor_sizes: [20, 10, 5, 1]
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 10
  layers_post_mp: 1
  dim_inner: 128
  layer_type: gensconv
  act: gelu
  residual: True
  dropout: 0.4
  agg: max
  batchnorm: True
#  normalize_adj: False
  gens:
    hop_att: True
    K: 5
    gamma: 0.6
    fea_drop: simpl
    base_model: gat
    concat: True
    heads: 1
    edge_dim: 128
    att_dropout: 0.0
    use_ffN: True
    diff_alpha: False
    norm_type: "batch"
optim:
#  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
