out_dir: results
metric_best: f1
wandb:
  use: True
  project: COCO
dataset:
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 50
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: inductive_node
  layers_pre_mp: 0
  layers_mp: 11
  layers_post_mp: 1
  dim_inner: 148
  layer_type: gensconv
  act: gelu
  residual: True
  dropout: 0.3
  batchnorm: True
#  agg: mean
  gens:
    hop_att: True
    K: 3
    gamma: 1.0
    fea_drop: simple
    base_model: gat
    concat: False
    heads: 1
    edge_dim: 148
    use_ffN: True
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
