out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: CIFAR10
  entity: expand-gnns
dataset:
  format: PyG-GNNBenchmarkDataset
  name: CIFAR10
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode+EquivStableLapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
prep:
  exp: True
  exp_algorithm: 'Hamiltonian'
  exp_deg: 5 # Algorithm will use 5 permutations or 5 Hamiltonian cycles, so actual degree will be 10
  add_edge_index: True # Set True if you want to add real edges beside expander edges
  num_virt_node: 1 # Set True if you want to add global node connections beside expander edges
  add_self_loops: False
posenc_EquivStableLapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  raw_norm_type: none
train:
  mode: custom
  batch_size: 12 #32<16<12
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 8 #
  layers_post_mp: 4 # 4<3<2?
  dim_inner: 88  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False #False > True
  act: relu
  dropout: 0.1 #0.1 >0.2
  residual: True
  agg: mean
  normalize_adj: False
  layer_type: gensconv
  init_res: False
  init_res_ratio: 0.0
  gens:
    hop_att: True
    K: 4 #
    gamma: 1.0
    fea_drop: simple # simple > normal
    base_model: gat
    concat: False
    heads: 1
    edge_dim: 88
    att_dropout: 0.0
    use_ffN: True #?
    diff_alpha: False
    norm_type: "batch"
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0 #0 > other
  base_lr: 0.001 #0.001>0.0005
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5 #5>10
