out_dir: results
metric_best: f1
num_workers: 4
wandb:
  use: True
  project: COCO
dataset:
  format: PyG-COCOSuperpixels
  name: edge_wt_region_boundary
  slic_compactness: 30
  task: graph  # Even if VOC is node-level task, this needs to be set as 'graph'
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: COCONode+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: COCOEdge
  edge_encoder_bn: False
#prep:
#  exp: True
#  exp_deg: 11 # Algorithm will use 11 permutations or 11 Hamiltonian cycles, so actual degree will be 22
#  add_edge_index: True # Set True if you want to add real edges beside expander edges
#  num_virt_node: 0 # Set True if you want to add global node connections beside expander edges
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 200
  eval_period: 1
  ckpt_period: 100
  eval_smoothing_metrics: True
model:
  type: custom_gnn
  loss_fun: weighted_cross_entropy
gnn:
  head: global_head
  layers_pre_mp: 1
  layers_mp: 9
  layers_post_mp: 1
  dim_inner: 80
  layer_type: gensconv
  act: gelu
  residual: True
  dropout: 0.1
  batchnorm: True
  pre_gnn_type: 'walk'
  gens:
    hop_att: True
    K: 10
    gamma: 0.1
    fea_drop: simple
    base_model: gat
    concat: True
    heads: 4
    edge_dim: 80
    att_dropout: 0.0
    use_ffN: True
    diff_alpha: False
    norm_type: "batch"
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10